# Choose an optional name for the datacenter
global:
  datacenter: minidc
  image: consul:latest
  imageK8S: hashicorp/consul-k8s:0.8.1 

# True if you want to enable the catalog sync. "-" for default.
syncCatalog:
  enabled: true

# Enable the Consul Web UI via a NodePort
ui:
  service:
    type: 'NodePort'

# Enable Connect for secure communication between nodes
connectInject:
  enabled: true
  imageConsul: consul:latest
  imageEnvoy: envoyproxy/envoy-alpine:latest
client:
  enabled: true
  grpc: true

# Use only one Consul server for local development
server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0

