apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: keycloak
  namespace: keycloak
spec:
  secretName: keycloak-certificate
  issuerRef:
    name: vault-issuer
  commonName: keycloak.testlab.local
  dnsNames:
  - keycloak.testlab.local